addons:
  apt:
    packages:
      - python-yaml

git:
  submodules: false

matrix:
  fast_finish: true
  include:
    - env: PLANG=js
      language: node_js
      node_js: "9"
    - env: PLANG=java  JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
    - env: PLANG=somns JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8

install:
  - pip install --user ReBench
  - if [ "$PLANG" = "js" ];   then npm install -g jshint; fi

script:
  - implementations/build-$PLANG.sh && rebench test.conf test-$PLANG
  - implementations/build-$PLANG.sh style
